env.BITBUCKET_SSH           = 'bitbucket-git-develop'
env.CLOUDFARE_TOKEN         = 'cloudfare-dns-dev'
env.AWS_CREDENTIALS         = 'aws-service-develop'
env.AWS_REGION              = 'us-east-2'
env.SLACK_CHANNEL           = '#jenkins_develop'
env.WORKSPACE               = '/var/jenkins_home/workspace'
env.ENVIRONMENT             = 'develop'